import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/** UUID primary key, generated by Postgres. */
export const id = uuid("id")
  .primaryKey()
  .default(sql`gen_random_uuid()`);

/** created_at / updated_at, present on every table. */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

/** Soft delete for user-editable tables. Synced/derived tables (fx_rates,
 * price_snapshots, tax_accruals, audit_log) are excluded on purpose. */
export const softDelete = {
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
};

/**
 * Money amount in integer minor units (bani, cents). Never floats or
 * decimals. bigint (not int4) because int4 overflows at ~21.4M RON in bani;
 * values are safe as JS numbers up to 2^53.
 */
export const moneyMinor = (name: string) => bigint(name, { mode: "number" });
