import {
  AppWindow,
  ArrowLeftRight,
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  CarTaxiFront,
  Cat,
  ChartCandlestick,
  ChartLine,
  ChartPie,
  CircleHelp,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flag,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  Handshake,
  HeartPulse,
  Home,
  Hotel,
  KeyRound,
  Landmark,
  Leaf,
  Lightbulb,
  Mountain,
  Music,
  Package,
  Paintbrush,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scale,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Split,
  SquareParking,
  Stethoscope,
  Ticket,
  TrainFront,
  TreePalm,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  Users,
  UtensilsCrossed,
  Wallet,
  WalletCards,
  WashingMachine,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICON_MAP = {
  Home,
  Building2,
  KeyRound,
  Sofa,
  Wrench,
  Hammer,
  Paintbrush,
  WashingMachine,
  Lightbulb,
  Zap,
  Flame,
  Droplets,
  Wifi,
  Phone,
  Smartphone,
  Tv,
  ShoppingCart,
  UtensilsCrossed,
  Coffee,
  Pizza,
  Wine,
  Beer,
  Car,
  Fuel,
  Bus,
  TrainFront,
  Bike,
  CarTaxiFront,
  SquareParking,
  ShoppingBag,
  Shirt,
  Gift,
  Scissors,
  Sparkles,
  Glasses,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  Baby,
  Dog,
  Cat,
  GraduationCap,
  BookOpen,
  Ticket,
  Film,
  Music,
  Gamepad2,
  Plane,
  Hotel,
  Bed,
  Mountain,
  TreePalm,
  Umbrella,
  Banknote,
  HandCoins,
  Coins,
  PiggyBank,
  Wallet,
  WalletCards,
  CreditCard,
  TrendingUp,
  TrendingDown,
  ChartLine,
  ChartPie,
  Percent,
  Briefcase,
  Users,
  Handshake,
  FileText,
  Receipt,
  Landmark,
  Scale,
  Shield,
  AppWindow,
  Cloud,
  Package,
  Repeat,
  Leaf,
  CircleHelp,
} as const satisfies Record<string, LucideIcon>;

export type CategoryIconName = keyof typeof CATEGORY_ICON_MAP;

export const CATEGORY_ICON_GROUPS = [
  {
    key: "homeHousing",
    icons: ["Home", "Building2", "KeyRound", "Sofa", "Wrench", "Hammer", "Paintbrush", "WashingMachine"],
  },
  {
    key: "utilitiesConnectivity",
    icons: ["Lightbulb", "Zap", "Flame", "Droplets", "Wifi", "Phone", "Smartphone", "Tv"],
  },
  {
    key: "foodDrink",
    icons: ["ShoppingCart", "UtensilsCrossed", "Coffee", "Pizza", "Wine", "Beer"],
  },
  {
    key: "transport",
    icons: ["Car", "Fuel", "Bus", "TrainFront", "Bike", "CarTaxiFront", "SquareParking"],
  },
  {
    key: "shoppingPersonal",
    icons: ["ShoppingBag", "Shirt", "Gift", "Scissors", "Sparkles", "Glasses"],
  },
  { key: "health", icons: ["HeartPulse", "Stethoscope", "Pill", "Dumbbell"] },
  { key: "familyLearning", icons: ["Baby", "Dog", "Cat", "GraduationCap", "BookOpen"] },
  {
    key: "leisureTravel",
    icons: ["Ticket", "Film", "Music", "Gamepad2", "Plane", "Hotel", "Bed", "Mountain", "TreePalm", "Umbrella"],
  },
  {
    key: "moneyInvesting",
    icons: ["Banknote", "HandCoins", "Coins", "PiggyBank", "Wallet", "WalletCards", "CreditCard", "TrendingUp", "TrendingDown", "ChartLine", "ChartPie", "Percent"],
  },
  {
    key: "businessObligations",
    icons: ["Briefcase", "Users", "Handshake", "FileText", "Receipt", "Landmark", "Scale", "Shield", "AppWindow", "Cloud"],
  },
  { key: "general", icons: ["Package", "Repeat", "Leaf", "CircleHelp"] },
] as const satisfies readonly {
  key: string;
  icons: readonly CategoryIconName[];
}[];

export const KIND_ICON_MAP = {
  transfer: ArrowLeftRight,
  salary: WalletCards,
  opening_balance: Flag,
  dividend: Coins,
  trade: ChartCandlestick,
} as const satisfies Partial<Record<string, LucideIcon>>;

export const SPLIT_ICON = Split;

export function isCategoryIconName(value: string): value is CategoryIconName {
  return Object.hasOwn(CATEGORY_ICON_MAP, value);
}
